doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: 'utf8mb4'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                server_version: '11.4.2-MariaDB'
            tenant:
                url: '%env(resolve:DATABASE_URL_TENANT)%'
                charset: 'utf8mb4'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
                server_version: '11.4.2-MariaDB'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: false
        enable_lazy_ghost_objects: true
        controller_resolver:
            auto_mapping: false
        entity_managers:
            default:
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    Main:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            tenant:
                connection: tenant
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false
                mappings:
                    Tenant:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Tenant'
                        prefix: 'App\Entity\Tenant'
                        alias: Tenant

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
